config/routes.rb
Rails.application.routes.draw do
  get 'rails/generate'

  get 'rails/controller'

  get 'rails/coupon'

  resources :user 
  resources :loyalty
  resources :store
  resources :coupon
  resources :purchase
  resources :sessions 

  get '/logout', to: 'sessions#destroy'

  root to: "user#show"

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
	belongs_to :loyalty
	belongs_to :store
	belongs_to :user
	belongs_to :purchase

end

app/models/loyalty.rb
class Loyalty < ActiveRecord::Base
	has_many :users
	belongs_to :store
	has_many :purchases

end

app/models/loyalty_program.rb
class LoyaltyProgram < ActiveRecord::Base
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	belongs_to :user
	belongs_to :coupon
	belongs_to :store

end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :purchases
	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base

	validates :first_name, presence: true
	validates :last_name, presence: true 
	validates :email, presence: true
	validates :password, presence: true
	has_secure_password

	has_many :loyaltys
	has_many :coupons
	has_many :purchases

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  before_action :auth 

  def auth 
  	unless current_user 
  		redirect_to new_session_url
	end
	end

	def current_user 
		User.find_by(id: session["user_id"])
	end


end

app/controllers/loyalty_controller.rb
class LoyaltyController < ApplicationController



end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
end

app/controllers/rails_controller.rb
class RailsController < ApplicationController
  def generate
  end

  def controller
  end

  def coupon
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :auth 
	layout false

	def create 
    
	    @user = User.find_by(email: params["email"])
		    if @user.present?
		    	  if @user.authenticate(params["password"])
    	    		session["user_id"] = @user.id
    	   			 redirect_to root_url
    	  		else
    	    redirect_to new_session_url, alert: 'Please try again'
    	  	end
    	else
      	redirect_to new_session_url, alert: 'Please try again'
    	end

	end

	def destroy
    session["user_id"] = nil
    redirect_to root_url, notice: "Logged out"

	end



end

app/controllers/store_controller.rb
class StoreController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	skip_before_action :auth, only: [:new, :create]

  def index
    @user = User.all	
	end
  
  def show
	@user = User.find_by(id: params["id"])	
    end

    def new
    	@user = User.new

    end

  def create
    @user = User.create(params["user"])
    if @user.valid?
      redirect_to users_path
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loyalty_helper.rb
module LoyaltyHelper
end

app/helpers/loyalty_program_helper.rb
module LoyaltyProgramHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KIEI 925 Final</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
    <div class="container">

      <% if notice %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      
      <nav class="navbar navbar-inverse" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to "Home", root_url, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <a href="/">
                <i class="fa fa-home"></i>
                Home
              </a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">

            <% if current_user.try(:admin?) %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  <i class="fa fa-cog"></i>
                  Admin
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Coupons", new_coupons_path %></li>
                  <li><%= link_to "Stores", new_store_path %></li>
                  <li><%= link_to "Users", new_user_path %></li>
                </ul>
              </li>
            <% end %>

            <% if current_user %>
              <li><%= link_to current_user.try(:name), root_url %></li>
              <li><%= link_to "Logout", logout_url %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>
    <div class="container">
      <%= yield %>
    </div>

<%= yield %>

</body>
</html>

app/views/loyalty/new.html.erb
<% if @loyalty.errors.any? %>
  <div class="alert alert-warning" role="alert">
    <% @loyalty.errors.full_messages.each do |message| %>
      <%= message %><br>
    <% end %>
  </div>
<% end %>


<h1> Choose a new loyalty program </h1>

<%= form_for @loyalty do |form| %>
  <div class="form-group">
    <%= form.label :store %>
    <%= form.collection_select(:store_id, Loyalty.all, :id, :store) %>
  </div>
  <div class="form-group">
    <%= form.label :program %>
    <%= form.text_field :program, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :program_num %>
    <%= form.text_field :program_num, class: "form-control" %>
  </div>
  <%= form.button 'Add loyalty program', class: "btn btn-success" %>
<% end %>

app/views/loyalty_program/new.html.erb
Choose a new loyalty program

<%= form_for @loyalty do |form| %>
  <div class="form-group">
    <%= form.label :store %>
    <%= form.collection_select(:store_id, Loyalty.all, :id, :store) %>
  </div>
  <div class="form-group">
    <%= form.label :program %>
    <%= form.text_field :program, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :program_num %>
    <%= form.text_field :program_num, class: "form-control" %>
  </div>
  <%= form.button 'Add loyalty program', class: "btn btn-success" %>
<% end %>

app/views/loyaltyp/edit.html.erb
<%= form_for @loyalty do |form| %>
  <div class="form-group">
    <%= form.label :store %>
    <%= form.text_field :store, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :program %>
    <%= form.text_field :program, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :program_num %>
    <%= form.text_field :program_num, class: "form-control" %>
  </div>
  <%= form.button 'Edit Program', class: "btn btn-success" %>
<% end %>

app/views/loyaltyp/new.html.erb
<%= form_for @newloyalty do |form| %>
  <div class="form-group">
    <%= form.label :store %>
    <%= form.text_field :store, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :program %>
    <%= form.text_field :program, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :program_num %>
    <%= form.text_field :program_num, class: "form-control" %>
  </div>
  <%= form.button 'Add loyalty program', class: "btn btn-success" %>
<% end %>

app/views/rails/controller.html.erb
<h1>Rails#controller</h1>
<p>Find me in app/views/rails/controller.html.erb</p>

app/views/rails/coupon.html.erb
<h1>Rails#coupon</h1>
<p>Find me in app/views/rails/coupon.html.erb</p>

app/views/rails/generate.html.erb
<h1>Rails#generate</h1>
<p>Find me in app/views/rails/generate.html.erb</p>

app/views/user/index.html.erb
<% @user.each do |user| %>
	<div class="col-sm-6">
	<div class="thumbnail">
		<a href="/user/<%= user.id%>">
	<p><%= user.first_name %> <%= link_to user.last_name, user_url(user) %></a></p>
	</div>
	</div>
<% end %>

app/views/user/new.html.erb
<%= form_for @loyalty do |form| %>
  <div class="form-group">
    <%= form.label :store %>
    <%= form.text_field :store, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :program %>
    <%= form.text_field :program, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :program_num %>
    <%= form.text_field :program_num, class: "form-control" %>
  </div>
  <%= form.button 'Add loyalty program', class: "btn btn-success" %>
<% end %>

app/views/user/show.html.erb
<h1> <%= @user.first_name %> <%= @user.middle_initial %> <%= @user.last_name %> </h1>
<p></p>



<h3> Loyalty Programs </h3>

<p> <%= @user.loyalty_id %> </p>

<% @user.user_id.each do |loyalty| %>
	<%= @user.loyalty.program %>
<% end %>

app/views/users/show.html.erb
<h1> <%= @users.first_name @users.middle_initial @users.last_name %> </h1>

<h3> Loyalty Programs </h3>

<p> <% @LoyaltyProgram.each do |LoyaltyProgram| %>
	<%= LoyaltyProgram.find_by(id: users.user_id).store %> 

<% end %>